name: 'actionbot'
description: 'Checks your repository workflows for references to actions against a defined allow/prohibit list'
author: 'Contrast Security Inc.'
branding:
  icon: check-circle
  color: green
inputs:
  policy:
    required: true
    description: 'Set to either `allow` or `prohibit`. When allow is the policy, any actions not on the list will be in violation. When prohibit is the policy, any actions on the list will be in violation.'
  policy-url:
    required: true
    description: 'The URL to a publicly accessible or private GitHub JSON file containing a list of allowed or prohibited actions. Private URLs require appropriate permissions or authentication.'
  fail-if-violations:
    required: false
    default: 'true'
    description: 'True to set the status of the action to Failed if violations occur. Set to false to allow downstream actions to execute. Defaults to true.'
  github-token:
    required: true
    description: 'Your GitHub token to access the files in the commits tied to the push or puill request.'
outputs:
  results:
      description: 'A list of any actions breaking the provided policy rules.'
runs:
  using: 'node20'
  main: 'lib/index.js'